services:
  - type: web
    name: serviq
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: ServiQ
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://serviq-wmt2.onrender.com
      - key: ASSET_URL
        value: https://serviq-wmt2.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    buildCommand: bash build.sh
    startCommand: bash start.sh
